title: Gdzienarower.eu
description: Odkrywaj Europę na dwóch kołach. Gdzienarower.eu to dom europejskiej turystyki rowerowej — tu zaczynają się Twoje rowerowe przygody.
name: Gdzienarower.eu
locale: pl-PL
timezone: Europe/Warsaw

atom_feed:
  hide: true

footer:
  links: []

lang: pl

# Ważne dla GitHub Pages:
# Na github.io URL jest stały, a baseurl musi być nazwą repo.
url: https://jraczk- anty.github.io
baseurl: /Gdzienarower.eu

remote_theme: mmistakes/minimal-mistakes

plugins:
  - jekyll-include-cache

minimal_mistakes_skin: contrast

logo: /assets/logo.png

search: false
breadcrumbs: false

collections:
  projects:
    output: true
    permalink: /projekty/:name/

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
  - scope:
      path: ""
      type: projects
    values:
      layout: single

# Blog (posts)
permalink: /journal/:categories/:title/
